<?php
require_once("autoloader.php");

function addTarea(){
    if ($_SERVER["REQUEST_METHOD"] == "POST") {
        $title = $_POST["title"];
        $description = $_POST["description"];
        $dueDate = $_POST["dueDate"];

        setlocale(LC_TIME, 'es_ES.UTF-8');
        $fecha_actual = date("Y-m-d");

        $conn = new Connection;
        $dataBase = $conn->getConn();

        $sql = "INSERT INTO tareas (titulo, descripcion, fecha_creacion, fecha_vencimiento) VALUES ('$title', '$description', '$fecha_actual', '$dueDate')";

        $resultado = mysqli_query($dataBase, $sql);

        if ($resultado) {
            echo "Los datos se han subido correctamente";
        } else {
            echo "Error al subir los datos: " . mysqli_error($dataBase);
        }
    }
}

addTarea();

?>

<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Nueva Tarea</title>
<link rel="stylesheet" type="text/css" href="form/view.css" media="all"> 
</head>
<body id="main_body">
    
    <img id="top" src="form/top.png" alt="">
    <div id="form_container">
    
        <h1><a>Nueva Tarea</a></h1>
        <form class="appnitro"  method="post" action="">
                    <div class="form_description">
            <h2>Nueva Tarea</h2>
            <p>Introduce los datos de la tarea</p>
        </div>                      
            <ul >
            
                    <li>
        <label class="description" for="title">Título </label>
        <div>
            <input name="title" id="title" class="element text medium" type="text" maxlength="255" value=""/> 
        </div> 
        </li>       <li>
        <label class="description" for="description">Descripción de la tarea </label>
        <div>
            <textarea name="description" id="description" class="element textarea medium"></textarea> 
        </div> 
        </li>       <li>
        <label class="description" for="dueDate">Fecha de vencimiento </label>
        <span>
            <input name="dueDate" id="dueDate"  class="element text" size="2" maxlength="2" value="" type="date">
        </span>     
        </li>
            
        <li class="buttons">
                <input type="hidden" name="id" value="12028" />
                <input class="button_text" type="submit" name="submit" value="Guardar" />
        </li>
            </ul>
        </form>    
        <div id="footer">
            Generated by <a href="http://www.floridauniversitaria.es">Florida</a>
        </div>
    </div>
    <img id="bottom" src="form/bottom.png" alt="">
    </body>
</html>
